version: "3"
services:
    koa:
        container_name: ${PROJECT_NAME}-koa
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        command: webpack --env.hmr --env.docker
        volumes:
            - .:/usr/app/
            - ./node_modules/:/usr/app/node_modules
        ports:
            - 3000:3000
            - 9230:9230
        environment:
            - PORT=3000
            - HOST=0.0.0.0
        links:
            - database
        network_mode: "bridge"
        depends_on:
            - phpmyadmin

    # Only used to install vendors
    vendors:
        build:
            context: ./
            dockerfile: ./docker/install/Dockerfile
        container_name: ${PROJECT_NAME}-vendors
        volumes:
            - .:/usr/app/
            - ./node_modules/:/usr/app/node_modules

    database:
        container_name: ${PROJECT_NAME}-db
        image: mariadb
        volumes:
            - ./var/lib/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_DATABASE=${TYPEORM_DATABASE}
            - MYSQL_USER=${TYPEORM_USERNAME}
            - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        network_mode: "bridge"

    phpmyadmin:
        container_name: ${PROJECT_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - VIRTUAL_HOST=phpmyadmin.${PROJECT_NAME}.lol
            - VIRTUAL_PORT=9000
            - MYSQL_USERNAME=${TYPEORM_USERNAME}
            - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
            - PMA_USERNAME=${TYPEORM_USERNAME}
            - PMA_PASSWORD=${TYPEORM_PASSWORD}
            - PMA_HOSTS=${TYPEORM_HOST}
        ports:
            - 9000:80
        links:
            - database
        network_mode: "bridge"
